# Set the message to "" to disable it
# Use {MONEY} to display the money they lost
# Use {BALANCE} to display the player's remaining balance
death-message: "&cYou lost ${MONEY} because you died!"
bypass-message: "&aYou didn't lose money because you're special!"

# How much should we take from the player when they die?
# Valid options are:
# amount-to-take: 15% - takes 15% of their balance
# amount-to-take: ALL - resets their balance to 0
# amount-to-take: 100.00 - takes $100 from their balance
amount-to-take: 0.00

# The format to use for displaying currencies
# The current format is used by most countries
currency-format: "#,##0.00"