main: me.jasonhorkles.expensivedeaths.ExpensiveDeaths
name: ExpensiveDeaths
description: Clear someone's balance when they die
version: %VERSION%
author: JasonHorkles
website: https://github.com/SilverstoneMC/ExpensiveDeaths
api-version: 1.17
depend:
  - Vault

commands:
  edrl:
    aliases: [ expensivedeathsrl, expensivedeathsreload ]
    description: "Reload the plugin"
    permission: expensivedeaths.reload

permissions:
  expensivedeaths.bypass:
    default: false
  expensivedeaths.reload:
    default: op