main: net.silverstonemc.expensivedeaths.ExpensiveDeaths
name: ExpensiveDeaths
description: Steal money when people die
version: %VERSION%
author: JasonHorkles
website: https://github.com/SilverstoneMC/ExpensiveDeaths
api-version: 1.16
depend:
  - Vault
softdepend:
  - PlaceholderAPI

commands:
  edrl:
    aliases: [ expensivedeathsrl, expensivedeathsreload ]
    description: "Reload the plugin"
    permission: expensivedeaths.reload

permissions:
  expensivedeaths.bypass:
    default: false
  expensivedeaths.reload:
    default: op